export const OPEN_WORK = 'OPEN_WORK'
export const CLOSE_WORK = 'CLOSE_WORK'
export const CHANGE_OP = 'CHANGE_OP'
export const GET_WORKS = 'GET_WORKS'
export const SUCCESS_GET_WORKS = 'SUCCESS_GET_WORK'
export const FAILURE_GET_WORKS = 'FAILURE_GET_WORKS'

export const GET_DATA_FIREBASE = 'GET_DATA_FIREBASE'
export const SUCCESS_GET_DATA_FIREBASE = "SUCCESS_GET_DATA_FIREBASE"
export const FAILURE_GET_DATA_FIREBASE = "FAILURE_GET_DATA_FIREBASE"
export const SET_LOAD = "SET_LOAD"
export const SET_ALERT = "SET_ALERT"
